### ISSUE TITLE
Question and answer flashcards

### ISSUE THREAD

**Issue by Ypot** [meedstrom/inline-anki#1]
Hi
I have just go through the readme, and I like the idea.

My way of using emphasis I think fits with your package: I use `/term/ and _definition_.`

My suggestion: what about using your idea to generate question and answer flashcards?
For example: 

```
_If the multiverse is real, I desire to believe the multiverse is real, and if the multiverse is not real, I desire to believe the multiverse is not real. Let me not become attached to beliefs I may not want._ 
/the Litany of Tarski/^1695193247518
```

Question would be: the Litany of Tarski
Answer would be the underlined text

**Comment by Ypot** [comment]
Although I am thinking that the default way would be very similar. Just interchanging the export of each emphasis would be enough to get similar results. For example clozing italics or clozing underline.

I am closing this issue till using your package at least.

Thanks!

**Comment by meedstrom** [comment]
Hi! You could also keep it as a cloze type, and cloze only the answer:

"If the multiverse is real, I desire to believe the multiverse is real, and if the multiverse is not real, I desire to believe the multiverse is not real. Let me not become attached to beliefs I may not want."  This is /the Litany of Tarski/.^1695193247518

The main problem with cloze is it's not clear what's being asked, so you have to contrive a a second sentence starting with "This is...". I would like to enable something like this single-column table:

    | If the multiverse is real, I desire to believe the multiverse is real;             |
    | and if the multiverse is not real, I desire to believe the multiverse is not real. |
    | Let me not become attached to beliefs I may not want."                             |  
    | /the Litany of Tarski/^1695193247518                                               |

But of course, the problem with that is you need manual linebreaks or it'll look bad.

On the roadmap is to make possible the following form, where the last line is taken as the answer.  If there are no clozes, then it'll be automatically interpreted as question-answer.

    #+begin_flashcard 1695193247518
    If the multiverse is real, I desire to believe the multiverse is real, and if the multiverse is not real, I desire to believe the multiverse is not real. Let me not become attached to beliefs I may not want."
    --The Litany of Tarski
    #+end_flashcard

Do you like that?
