### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by Ypot** [meedstrom/inline-anki#4]
Hi

I have some tests in PDF that I would like to turn into anki flashcards. Do you think your package could do it? How would you do it?

1. Question 1
a) Option a
b) Option b
c) Option c
Correct: b. Because ....

2. Question 2
...

Bests!!

**Comment by meedstrom** [comment]
Maybe this?

```
#+begin_flashcard
Question 1
a) Option a
b) Option b
c) Option c
Correct: _b. Because of this and that_
#+end_flashcard
```

I'd really advise writing flashcards in your own words though.
